[paths]
watch_path = /mnt/sda7.1
flag_file  = /mnt/sda7.1/.sanctuary_mode

[archetypes]
markers = ssuccubus,theincubus,vvampire,vulturite,jellybean

[tokens]
block_tokens = ssuccubus,theincubus,vvampire,vulturite,jellybean
